### PR TITLE
Feature/button disabled theme

### PR DESCRIPTION
**Pull request by kandrelczyk**
Here's the theme. I'm not sure about the shades of gray. I think the work fine in respect of contrast but let me know what you think.

### CODE REVIEW

**Comment by kandrelczyk** [comment]
No problem, changed. 

Another thing I'm missing is 'invalid' state for the input components. Passing 'invalid=true' could change the border to --color-error. I can add it for Input, InputNumber and AutoComplete. What do you think?

**Comment by luoxiaozero** [comment]
You can add disabled parameters to Input, InputNumber, and AutoComplete.  The style can refer to https://www.naiveui.com/en-US/light/components/input#disabled.vue and https://hope-ui.com/docs/data-entry/input#disabled

**Comment by luoxiaozero** [comment]
Thank you for your work.

**Comment by kandrelczyk** [comment]
No problem. I will add disabled params next, as you suggested.
 What about 'invalid' param like here: https://hope-ui.com/docs/data-entry/input#invalid ?

**Comment by luoxiaozero** [comment]
Just now, I misunderstood, you can add the `invalid` parameter.

**Comment by luoxiaozero** [comment]
You can also add the status parameters to achieve the same effect, https://www.naiveui.com/en-US/light/components/input#status.vue

**Comment by luoxiaozero** [comment]
Let's use the `invalid` parameter. I haven't used 'warning' status either.

**Pull request merged**
