### PR TITLE
Added width property to Modal dialog

### PR DESCRIPTION
**Pull request by glennpierce**
Added width property to Modal dialog

### CODE REVIEW

**Comment by glennpierce** [comment]
Thanks. Sorry about the animation. Trying to learn my way around thaw internals.

**Comment by luoxiaozero** [comment]
Merge now.

**Comment by glennpierce** [comment]
Sorry I can't get the dialog to change width now.

<Modal width="1200px;" show mask_closeable=true>

or

<Modal width="50%;" show mask_closeable=true>

Shows the same size . Unless I am doing something dumb which is a distinct possibility.

**Comment by luoxiaozero** [comment]
Can you write a minimal repetition example?

**Pull request merged**
