### PR TITLE
feat: Add min/max props into InputNumber

### PR DESCRIPTION
**Pull request by wiyota**
Hello @luoxiaozero 

Added range with min/max props to InputNumber component.

When the input value reaches the limit, the plus/minus icon will be disabled.
If it goes out of range, the component will be invalid and will automatically fall within the range on blur.

### CODE REVIEW

**Comment by luoxiaozero** [comment]
Thank you, great. Can you add relevant documentation to the `demo_markdown\docs\input_number\mod.md` file?

**Comment by luoxiaozero** [comment]
This is a breakthrough change, so I marked it 0.3.

**Comment by wiyota** [comment]
I am honored!

I have refactored the component and added the Min / Max section to docs, but where should I insert the demo and props?
I placed them at the end for now, but I think it would be clearer to put the props after the step and then the Min / Max section above the Disabled section.

**Comment by luoxiaozero** [comment]
> but I think it would be clearer to put the props after the step and then the Min / Max section above the Disabled section.

It would be better

**Comment by wiyota** [comment]
Then I will do so.

Also, the doc currently list `num_traits::Bounded` as a required trait for T (since that is the actual implementation), but I thought it would be clearer to mention `num`, which is the meta-crate for `num_traits`, so list it as `num::Bounded`.

I will make these changes to the doc and commit.

**Comment by luoxiaozero** [comment]
thank you.

**Pull request merged**
