### PR TITLE
Allow label to be any type that impl IntoView

### PR DESCRIPTION
**Pull request by heyjul**
#201

### CODE REVIEW

**Comment by heyjul** [comment]
I see that the builds fails, I will try to fix that later today

**Comment by luoxiaozero** [comment]
I think the build failed because it was a breaking change.

**Comment by heyjul** [comment]
Yes it is indeed. 
I thought that it would not be a breaking change since String implements the necessary traits and since the type can be inferred but I didn't think about return types of a function. 
Now that I think about it, it will probably be a problem even when no options are passed down to the AutoComplete. 

Since it is a breaking change, is it still a desired change ?

**Comment by heyjul** [comment]
Can't think of a way to implement this.

**Comment by luoxiaozero** [comment]
I will change it in version 0.4.

**Pull request closed without merging**
