### PR TITLE
Fluent/dropdown

### PR DESCRIPTION
**Pull request by kandrelczyk**
Hi, 

I finally had some time to move dropdown into fluent branch. I will fix the menu in site header next.

### CODE REVIEW

**Comment by luoxiaozero** [comment]
Hi, I want to make the components of the thaw/fluent branch as consistent with fluent-ui as possible, so I think you can change the DropdownTrigger to optional, and when it is empty, it will be consistent with the style of the [Dropdown](https://react.fluentui.dev/?path=/docs/components-dropdown--default) component of fluent-ui.

You can also refer to the implementation of [Combobox](https://github.com/thaw-ui/thaw/blob/thaw/fluent/thaw/src/combobox/combobox.rs).

**Comment by kandrelczyk** [comment]
Sure, I will do it tomorrow.

**Comment by kandrelczyk** [comment]
Ok, after taking a closer look I think the component I was aiming for is more like the Menu component from fluent-ui (https://react.fluentui.dev/?path=/docs/components-menu-menu--default). It's called 'dropdown' in naive (https://www.naiveui.com/en-US/os-theme/components/dropdown) and we already had a Menu in Thaw 0.3 (https://thaw-ui.github.io/thaw/components/menu) so I called it Dropdown. I wanted to add sub-menus in the future. Should I just rename it?

**Comment by kandrelczyk** [comment]
In the meantime I finished the mobile menu in demo page using the new dropdown component. Please check if it's fine. 
One issue: the github and discord links break the page and I can't figure out why. After clicking on those elements the on_enter/on_leave events produce errors. Can you take a look?

**Comment by luoxiaozero** [comment]
> Should I just rename it?

Yes, I think it's necessary to be consistent with fluent ui.

> Can you take a look?

I'll go look at the code.

**Comment by luoxiaozero** [comment]
I haven't reproduced this issue, could you tell me the steps to reproduce it? (You can update your code to the latest thaw/fluent branch.)

**Pull request closed without merging**
