### PR TITLE
feature: closable messages and message position

### PR DESCRIPTION
**Pull request by kandrelczyk**
Hi,

This isn't ready but please check if it makes sense. This adds optional close button to messages, permanent messages (since now we can close manually) and configurable message positions.  If it's ok I will add top-right, top-left, bottom-right, bottom-left positions and update documentation.

### CODE REVIEW

**Comment by luoxiaozero** [comment]
I feel like `can_close` could be changed to `closable`, which defaults to `false`.

**Comment by kandrelczyk** [comment]
Changed the can_close param, added rest of the positions and updated documentation. Let me know if anything else should be changed.

**Comment by luoxiaozero** [comment]
close

There is also a problem with the style of the close button.  You can refer to https://www.naiveui.com/en-US/light/components/message#closable.vue

**Comment by kandrelczyk** [comment]
Sure, I was following chakra ui and placed it in the upper right corner but the way NaiveUI does it is better. Changed.

**Comment by luoxiaozero** [comment]
Hi, You can read my review above.

**Comment by kandrelczyk** [comment]
Sorry, all I see is the comment about the close button. Which review?

**Comment by luoxiaozero** [comment]
github

Can you see the red box here?

**Comment by kandrelczyk** [comment]
Hi, I can't see this review. Apparently it's a known issue in github: https://github.com/orgs/community/discussions/4427

I don't see any reviews so I don't know where to find it. 

image

I did applied comments visible in the screenshot you posted. If there are more comments you will have to add me to this review somehow.

**Comment by luoxiaozero** [comment]
I'm sorry. It's my fault.

thaw/src/auto_complete/mod.rs
```diff
                }
            });
        } else if key == *"Enter" {
+          event.prevent_default();
            let option_value = options.with_untracked(|options| {
                let index = select_option_index.get_untracked();
                if options.len() > index {
```

What is the reason for adding this line of code?

**Comment by kandrelczyk** [comment]
Hi, no problem. As for the prevent_default, pressing Enter in the AutoComplete element to select an option submits the entire form and reloads the page. It should probably be a separate branch, I just came across this when working on the messages.


This could be avoided by not using <form> at all but I think it should be possible to use data input elements with <form on:submit=...> so they should not submit in cases like this. What do you think?

**Comment by luoxiaozero** [comment]
Good. Now merge.

**Pull request merged**
